name: Site

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: site/package-lock.json
        
    - name: Change directory
      run: cd site
    
    - name: Install dependencies
      working-directory: ./site
      run: npm ci
    
    - name: Check site formatting
      working-directory: ./site
      run: npm run format:check
    
    - name: Build Vite site
      working-directory: ./site
      run: npm run build
